<center><big><b>Bienvenido a TensorFlow</b></big></center>
<img src="images/LOGO.jpeg">

<big><b>Agenda</b></big>
<ul>
  <li>Básicas de Tensorflow</li>
</ul>
<br>
<big><b>Es necesario indicar que existen 3 tipos de tensores</b></big>
<ul>
  <li>Constantes</li>
  <li>Variables</li>
  <li>Placeholders</li>
</ul>

<big><b>algo importante antes de empezar </b></big>
<br>
tf.multiply(X, Y) hace la multiplicación elemento a elemento
<br>
tf.matmul(X, Y) hace multiplicación de matrices

In [1]:
#Básicas de Tensorflow - constantes
import tensorflow as tf
x1 = tf.constant('Hola')#la información de este tipo de dato es no cambia, es invariable, inmutable...
y1 = tf.constant('Mundo')#la información de este tipo de dato es no cambia, es invariable, inmutable...
print y1
with tf.Session() as session:
    print(session.run(x1 + ' ' + y1))
session.close()

Hola Mundo
Tensor("Const_1:0", shape=(), dtype=string)
Hola Mundo


In [ ]:
# forma de una constante: tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False)

In [65]:
#Básicas de Tensorflow - constantes
c = tf.constant([2, 2])
d = tf.constant([[0, 1], [2, 3]])
e = tf.zeros([5], dtype=tf.float32)
f = tf.zeros([2, 3], dtype=tf.float32)
g = tf.ones_like(f)
h = tf.fill([2, 3], 8) 
with tf.Session() as session:
    print session.run(c)
    print session.run(d)
    print session.run(e)
    print session.run(f)
    print session.run(g)
    print session.run(h)
session.close()

[2 2]
[[0 1]
 [2 3]]
[ 0.  0.  0.  0.  0.]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [68]:
#tf.linspace(start, stop, num) 
w=tf.linspace(10.0, 13.0, 4) 
# 'limit' is 5
y=tf.range(5)
with tf.Session() as session:
    print session.run(w)
    print session.run(y)
session.close()

[ 10.  11.  12.  13.]
[0 1 2 3 4]


In [3]:
#Básicas de tensorflow - Variables
import tensorflow as tf
a = tf.constant([35, 40, 45])
b = tf.Variable(a + 5)
#Inicialización de todas las variables
model = tf.global_variables_initializer()
with tf.Session() as session:
    #Inicio de sesión de todas las variables
    session.run(model)
    print session.run(b)
session.close()


[40 45 50]


In [4]:
#Básicas de tensorflow - Variables
import tensorflow as tf

var1 = tf.Variable([[1, 2], [1, 2]])
var2 = tf.Variable([[3, 4], [3, 4]])

result = tf.matmul(var1, var2)
#Inicialización de todas las variables
model = tf.global_variables_initializer()

with tf.Session() as sess:
    #Inicio de sesión de todas las variables
    sess.run(model)
    print sess.run(result)
    


[[ 9 12]
 [ 9 12]]


In [5]:
#Básicas de tensorflow - Placeholders
import tensorflow as tf
#placeholder se utiliza para asignar un valor más adelante
a = tf.placeholder("float")
b = tf.placeholder("float")
y = tf.multiply(a, b)
sess = tf.Session()
print sess.run(y, feed_dict={a: 3, b: 3})

y = tf.multiply(y,2)

print y

print sess.run(y, feed_dict={a: 4, b: 4})

9.0
Tensor("Mul_1:0", dtype=float32)
32.0


Existe la necesidad de identificar que tan efectivas son las operaciones proporcionadas por Tensorflow. A continuación, se visualiza el tiempo de ejecución de dos algoritmos con y sin Tensorflow:

In [6]:
import time 
import tensorflow as tf

a = tf.random_normal([1000], mean=-1, stddev=4)
b = tf.random_normal([1000], mean=-1, stddev=4)
c = tf.multiply(a,b)

sess = tf.Session()
tic = time.time()
sess.run(c)
toc = time.time()
sess.close()
print ""
print "Tiempo de ejecución con Tensorflow "+str(1000*(toc-tic))  +" ms"
print ""


Tiempo de ejecución con Tensorflow 42.6790714264 ms



In [7]:
c=0
tic = time.time()
for i in range(1000):
    c+=a[i]*b[i]
toc = time.time()
print ""
print "Tiempo de ejecución sin Tensorflow "+str(1000*(toc-tic))  +" ms"
print ""


Tiempo de ejecución sin Tensorflow 46411.2181664 ms



In [60]:
# tf.placeholder(dtype, shape=None, name=None)
# crea un placeholder de tipo float 32-bit, shape es un vector 3 elementos
a = tf.placeholder(tf.float32, shape=[3])
# crea una constante de tipo float 32-bit, shape es un vector 3 elementos
b = tf.constant([5, 5, 5], tf.float32)
c = a + b # equivalente a c = tf.add(a,b)
with tf.Session() as sess:
    print sess.run(c) 

In [59]:
# tf.placeholder(dtype, shape=None, name=None)
# crea un placeholder de tipo float 32-bit, shape es un vector 3 elementos
a = tf.placeholder(tf.float32, shape=[3])
# crea una constante de tipo float 32-bit, shape es un vector 3 elementos
b = tf.constant([5, 5, 5], tf.float32)
c = a + b # equivalente a c = tf.add(a,b)
with tf.Session() as sess:
    print sess.run(c, feed_dict={a : [1,2,3]}) 

[ 6.  7.  8.]
