<center><b>Bienvenido a TensorFlow</b></center>
<img src="images/LOGO.jpeg">

<b>Tensors</b>
<br>
Esta secuencia de comandos presenta varias formas de crear tensores en TensorFlow Primero comenzamos cargando TensorFlow y restableciendo el gráfico computacional.

In [1]:
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

<b>Iniciar una sesión</b>
<br>
Obtener el control del gráfico con tf.Sesión ()

In [2]:
sess = tf.Session()

<b>Creando tensores</b>
<br>
Tensorflow tiene una función incorporada para crear tensores para usar en variables. Por ejemplo, podemos crear un tensor lleno de cero de forma predefinida usando la función tf.zeros() de la siguiente manera.

In [3]:
tensor = tf.zeros([1,20])

Los algoritmos de TensorFlow necesitan saber qué objetos son variables y cuáles son constantes. La diferencia entre estos dos objetos se explicará más adelante. Por ahora, creamos una variable usando la función TensorFlow tf.Variable() de la siguiente manera.

In [6]:
var = tf.Variable(tf.zeros([1,20]))

Tenga en cuenta que no puede ejecutar sess.run(var), esto daría lugar a un error. Debido a que TensorFlow opera con gráficos computacionales, tenemos que crear una operación de inicialización de variables para evaluarlas. Veremos más de esto más adelante. Para este script, podemos inicializar una variable a la vez llamando al método variable var.initializer.

In [7]:
sess.run(var.initializer)
sess.run(var)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

Comencemos primero creando variables de forma específica declarando el tamaño de nuestra fila y columna.

In [8]:
dim_fila = 2
dim_col = 3

Aquí utilizamos variables inicializadas para contener todos los ceros o unos.

In [9]:
zero_var = tf.Variable(tf.zeros([dim_fila, dim_col]))
ones_var = tf.Variable(tf.ones([dim_fila, dim_col]))

De nuevo, se debe llamar al método de inicialización de nuestras variables y ejecutarlas para evaluar sus contenidos.

In [13]:
sess.run(zero_var.initializer)
sess.run(ones_var.initializer)
print(sess.run(zero_var))
print(sess.run(ones_var))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]


<b>Llenar un tensor con una constante</b>
<br>
A continuación, se llena un tensor con una constante.

In [18]:
var_1 = tf.Variable(tf.fill([dim_fila, dim_col], -2))
sess.run(var_1.initializer)
print(sess.run(var_1))

[[-2 -2 -2]
 [-2 -2 -2]]


También podemos crear una variable a partir de una matriz o lista de constantes

In [19]:
# Crea una variable a partir de una constante
const_var = tf.Variable(tf.constant([4, 6, 7, 5, 3, 0, 9]))
# Esto también se puede usar para llenar una matriz:
const_fill_var = tf.Variable(tf.constant(-1, shape=[dim_fila, dim_col]))

sess.run(const_var.initializer)
sess.run(const_fill_var.initializer)

print(sess.run(const_var))
print(sess.run(const_fill_var))

[4 6 7 5 3 0 9]
[[-1 -1 -1]
 [-1 -1 -1]]


<b>Crear tensores basados en secuencias y rangos</b>
<br>
También podemos crear tensores a partir de funciones generadoras de secuencia en TensorFlow. La función TensorFlow linspace() y range() funcionan de forma muy similar a los equivalentes python y numpy respectivamente.


In [22]:
lineal = tf.Variable(tf.linspace(start=0.0, stop=1.0, num=3)) # Genera [0.0, 0.5, 1.0] 

secuencia = tf.Variable(tf.range(start=6, limit=15, delta=3)) # Genera [6, 9, 12] 

sess.run(lineal.initializer)
sess.run(secuencia.initializer)

print(sess.run(lineal))
print(sess.run(secuencia))

[ 0.   0.5  1. ]
[ 6  9 12]


<b>Tensores de números aleatorios</b>
<br>
También podemos inicializar tensores que provienen de números aleatorios como el siguiente.

In [28]:
random_norm = tf.random_normal([dim_fila, dim_col], mean=0.0, stddev=1.0)
random_unif = tf.random_uniform([dim_fila, dim_col], minval=0, maxval=4)

print(sess.run(random_norm))
print(sess.run(random_unif))
print(random_norm.shape)

[[ 0.48062307 -0.48991078  1.46397889]
 [-0.11555578  1.03812373  1.37628388]]
[[ 1.21033573  2.31537199  1.43372631]
 [ 3.88599634  2.27943468  0.58847237]]
(2, 3)


<b>Visualización a partir de TensorBoard</b>

In [33]:
# Reiniciar el grafo
ops.reset_default_graph()

# Iniciando la sesión 
sess = tf.Session()

# Creando una variable
var = tf.Variable([[1,2,3,4]])

# Inicialización y escritura sobre el grafo
writer = tf.summary.FileWriter("./temp/", graph=sess.graph)

# Inicialización de la operación
initialize_op = tf.global_variables_initializer()

# Ejecutar la inicialización de la variable
sess.run(initialize_op)

<b>Variables y Placeholders</b>
<br>
<b>Declarar placeholders</b>
<br>
Declaramos un placeholders utilizando la función de TensorFlow, tf.placeholder(), que acepta un argumento de tipo (tf.float32) y un argumento de forma, (4,4). Tenga en cuenta que la forma puede ser una tupla o una lista, [4,4].

In [72]:
x = tf.placeholder(tf.float32, shape=(4, 4))
x_1 = tf.placeholder(tf.float32, shape=(4, 4))

Para ilustrar cómo usar un placeholder, creamos datos de entrada para él y una operación que podemos visualizar en Tensorboard. Tenga en cuenta el uso de feed_dict, donde introducimos el valor de x en el grafo computacional.

In [74]:
import numpy as np

# Ingrese los datos en el marcador de posición, tenga en cuenta que 'array' y 'x' tienen la misma forma.
array = np.random.rand(4,4)
print(array)
# Crea un Tensor para realizar una operación (aquí, y será igual a x, una matriz de 4x4)
y = x * x_1 

sess = tf.Session()

# Se introduce el valor de x en el grafo computacional
print(sess.run(y, feed_dict={x: array, x_1:array}))

[[ 0.33836744  0.29862542  0.51653853  0.65204737]
 [ 0.96259927  0.33817624  0.39165996  0.2852697 ]
 [ 0.93078481  0.79571572  0.19793095  0.61186732]
 [ 0.46129682  0.21569596  0.18384062  0.9614113 ]]
[[ 0.11449252  0.08917713  0.26681203  0.4251658 ]
 [ 0.92659736  0.11436318  0.15339753  0.0813788 ]
 [ 0.86636037  0.63316357  0.03917666  0.3743816 ]
 [ 0.21279477  0.04652475  0.03379737  0.9243117 ]]


In [78]:
# Reiniciar el grafo
ops.reset_default_graph()
# crea un placeholder de tipo float 32-bit, shape es un vector 3 elementos
a = tf.placeholder(tf.float32, shape=[3])
# crea una constante de tipo float 32-bit, shape es un vector 3 elementos
b = tf.constant([5, 5, 5], tf.float32)
c = a + b # equivalente a c = tf.add(a,b)
with tf.Session() as sess:
    # Inicialización y escritura sobre el grafo
    writer = tf.summary.FileWriter("./temp2/", graph=sess.graph)
    print sess.run(c, feed_dict={a : [1,2,3]})

[ 6.  7.  8.]


<b>Matrices y Operaciones</b>
<br>
<b>Declarando matrices</b>
<br>
Matriz identidad:



In [80]:
identity_matrix = tf.diag([1.0,1.0,1.0])
sess = tf.Session()

print(sess.run(identity_matrix))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Matriz norma aleatoria 2x3:


In [81]:
A = tf.truncated_normal([2,3])
print(sess.run(A))

[[-1.09666383 -0.27636975  0.05493239]
 [-0.87236619 -1.34907997  1.55692649]]


Matriz constante 2x3:

In [82]:
B = tf.fill([2,3], 5.0)
print(sess.run(B))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


Matriz uniforme al azar 3x2:

In [95]:
C = tf.random_uniform([3,2])
print(sess.run(C))

[[ 0.51399267  0.51623952]
 [ 0.1822263   0.74697077]
 [ 0.93820345  0.31535494]]


Creando una matriz a partir de numpy:

In [89]:
D = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]]))
print(sess.run(D))
print D.shape

[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]
(3, 3)


<b>Matriz Operaciones</b>

In [90]:
print(sess.run(A+B))
print(sess.run(B-B))

[[ 4.43833351  4.66479921  4.70165777]
 [ 6.17652369  5.2548151   6.05221653]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [91]:
print(sess.run(tf.matmul(B, identity_matrix)))


[[ 5.  5.  5.]
 [ 5.  5.  5.]]


Matrix Transpuesta:

In [96]:
print(sess.run(tf.transpose(C)))

[[ 0.18222654  0.26450145  0.76856899]
 [ 0.67946672  0.02408278  0.80925453]]


Determinante de la matriz:


In [97]:
print(sess.run(tf.matrix_determinant(D)))


-38.0


Matriz inversa:


In [98]:
print(sess.run(tf.matrix_inverse(D)))


[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]
